# Assignment_11

#### Q1. Write the Python code to implement a single neuron.

**Ans.** 


In [1]:
from numpy import exp, array, random, dot, tanh
class my_network():
    
    def __init__(self):
        random.seed(1)
        # 3x1 Weight matrix
        self.weight_matrix = 2 * random.random((3, 1)) - 1
    
    def my_tanh(self, x):
        return tanh(x)
    
    def my_tanh_derivative(self, x):
        return 1.0 - tanh(x) ** 2
    
    # forward propagation
    def my_forward_propagation(self, inputs):
        return self.my_tanh(dot(inputs, self.weight_matrix))
    
    # training the neural network.
    def train(self, train_inputs, train_outputs,num_train_iterations):
        for iteration in range(num_train_iterations):
            output = self.my_forward_propagation(train_inputs)
            # Calculate the error in the output.
            error = train_outputs - output
        adjustment = dot(train_inputs.T, error *self.my_tanh_derivative(output))
          # Adjust the weight matrix
        self.weight_matrix += adjustment
          
# Driver Code
if __name__ == "__main__":
    my_neural = my_network()
    print ('Random weights when training has started')
    print (my_neural.weight_matrix)
    train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    train_outputs = array([[0, 1, 1, 0]]).T
    my_neural.train(train_inputs, train_outputs, 10000)
    print ('Displaying new weights after training')
    print (my_neural.weight_matrix)
    
    # Test the neural network with a new situation.
    print ("Testing network on new examples ->")
    print (my_neural.my_forward_propagation(array([1, 0, 0])))


Random weights when training has started
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Displaying new weights after training
[[1.95024663]
 [1.96483841]
 [1.96038419]]
Testing network on new examples ->
[0.96033857]


#### Q2. Write the Python code to implement ReLU.

**Ans.** 


In [2]:
def relu(x):
    return max(0.0, x)

x = 1.0
print('Applying Relu on (%.1f) gives %.1f' % (x, relu(x)))
x = -10.0
print('Applying Relu on (%.1f) gives %.1f' % (x, relu(x)))
x = 0.0
print('Applying Relu on (%.1f) gives %.1f' % (x, relu(x)))
x = 15.0
print('Applying Relu on (%.1f) gives %.1f' % (x, relu(x)))
x = -20.0
print('Applying Relu on (%.1f) gives %.1f' % (x, relu(x)))

Applying Relu on (1.0) gives 1.0
Applying Relu on (-10.0) gives 0.0
Applying Relu on (0.0) gives 0.0
Applying Relu on (15.0) gives 15.0
Applying Relu on (-20.0) gives 0.0


#### Q3. Write the Python code for a dense layer in terms of matrix multiplication.

**Ans.** 


In [3]:
import numpy as np 

## using random numbers generator,
np.random.seed(0)

# define our dataset 

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

#define dense layer class

class Dense_layer:
    def __init__(self, n_inputs, n_neurons):
        """
        2 arguments: number of inputs and numbers of neurons
        generate weight randomly and multiply with 0.1 to make the numbers smaller (between 0, 1)
        generate bias  
        """
        self.weight = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.bias = np.zeros((1, n_neurons))
    
    # define the forward function, it takes only 1 arrg : input (the dataset)
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weight) + self.bias

#### Q4. Write the Python code for a dense layer in plain Python (that is, with list comprehensions and functionality built into Python).

**Ans.** 


In [4]:
import random

class DenseLayer:
    def __init__(self, input_size, output_size):
        self.weights = [[random.random() for _ in range(output_size)] for _ in range(input_size)]
        self.bias = [random.random() for _ in range(output_size)]
    
    def forward(self, inputs):
        z = [sum([inputs[i] * self.weights[i][j] for i in range(len(inputs))]) + self.bias[j] for j in range(len(self.bias))]
        return z
    
# create a dense layer with 2 inputs and 3 outputs
layer = DenseLayer(2, 3)

# get input values from the user
input1 = float(input("Enter input 1: "))
input2 = float(input("Enter input 2: "))

# make a prediction based on the inputs
inputs = [input1, input2]
output = layer.forward(inputs)

print("The predicted output is:", output)

Enter input 1: 22
Enter input 2: 55
The predicted output is: [68.64912824528332, 70.53808420560202, 45.51663263913876]


#### Q5. What is the “hidden size” of a layer?

**Ans.** The number of hidden neurons should be between the size of the input layer and the size of the output layer. The number of hidden neurons should be 2/3 the size of the input layer, plus the size of the output layer. The number of hidden neurons should be less than twice the size of the input layer.

#### Q6. What does the t method do in PyTorch?

**Ans.** Returns a view of this tensor with its dimensions reversed.
If n is the number of dimensions in x, x.T is equivalent to x.permute(n-1, n-2, ..., 0).
The use of Tensor.T() on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider mT to transpose batches of matrices or x.permute(*torch.arange(x.ndim - 1, -1, -1)) to reverse the dimensions of a tensor

#### Q7. Why is matrix multiplication written in plain Python very slow?

**Ans.** Python is the most popular programming language for data-science-related tasks. And many of those tasks are computation-heavy ones. One of them is matrix multiplication – a basic linear algebra operation, used by almost all ML algorithms, for example, to compute activations of layers of a neural network based on activations.Python is a simple language with great tooling, enormous community, and a lot of packages available. But it is too slow for running computational-heavy algorithms, crucial for any data science task. However, there is a simple bypass for this limit. We can use libraries like NumPy, which provides a nice Python API for running code written in faster languages.
We can have the performance of those languages, without their complexity. And we can still use an ecosystem of Python packages, tooling, and community. In the case of using Python for data science, we not only shouldn’t reinvent the wheel – we mustn’t do it.

#### Q8. In matmul, why is ac==br?

**Ans.** If there is mismatch in dimensions, and one vector is longer than the other, we can no longer carry out element wise multiplication.The dimensions of the resulting matrix will always be ar,bc. That is the number of rows comes from A and the number of columns comes from B.

Here’s how it looks like in code:

In [5]:
import numpy as np

def matmul1(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    p=(ar,bc)
    c = np.zeros(p)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): #or br
                c[i,j] += a[i,k]*b[k,j]
    return c
mat1=np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
mat2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

result = matmul1(mat1, mat2)
print('Result: ', '\n', result)
print('Shape: ', result.shape)

Result:  
 [[15. 18. 21. 24.]
 [30. 36. 42. 48.]
 [45. 54. 63. 72.]
 [60. 72. 84. 96.]]
Shape:  (4, 4)


#### Q9. In Jupyter Notebook, how do you measure the time taken for a single cell to execute?

**Ans.** 
In Jupyter Notebook (IPython), you can use the magic commands `%timeit` and `%%timeit` to measure the execution time of your code. No need to import the timeit module.
`%timeit`
For `%timeit`, specify the target code after `%timeit` with a space.

By default, number and repeat in `timeit.timeit()` are set automatically. It can also be specified with `-n` and `-r` options.

The mean and standard deviation are calculated.

`%%timeit`
You can use the magic command `%%timeit` to measure the execution time of the cell.

As an example, try executing the same process using NumPy. As with `%timeit`, `-n` and `-r` are optional.

Note that `%%timeit` measures the execution time of the entire cell.

#### Q10. What is elementwise arithmetic?

**Ans.** An element-wise operation is an operation between two tensors that operates on corresponding elements within the respective tensors. An element-wise operation operates on corresponding elements between tensors. Two elements are said to be corresponding if the two elements occupy the same position within the tensor.

#### Q11. Write the PyTorch code to test whether every element of a is greater than the corresponding element of b.

**Ans.** 


In [1]:
# !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

import torch

ModuleNotFoundError: No module named 'torch'

In [7]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([0, 2, 2])

result = torch.gt(a, b)

if torch.all(result):
    print("All elements of a are greater than b")
else:
    print("Not all elements of a are greater than b")
    print("Indices where the condition fails: ", torch.where(result == False))

ModuleNotFoundError: No module named 'torch'

#### Q12. What is a rank-0 tensor? How do you convert it to a plain Python data type?

**Ans.** A tensor with rank 0 is a zero-dimensional array. The element of a zero-dimensional array is a point. This is represented as a Scalar in Math and has magnitude. Eg: s = 48.3. Shape - [].you can cast the datatype of a tensor to a new datatype by using the tf. cast function.
We can access the data type of a tensor using the ". dtype" attribute of the tensor. It returns the data type of the tensor.

#### Q13. How does elementwise arithmetic help us speed up matmul?

**Ans.** 
**elementwise** (not comparable) (mathematics). Obtained by operating on one element (of a matrix etc) at a time.
The element wise multiplication operator (#) computes a new matrix with elements that are the products of the corresponding elements of matrix1 and matrix2. In addition to multiplying matrices that have the same dimensions, you can use the element wise multiplication operator to multiply a matrix and a scalar.


#### Q14. What are the broadcasting rules?

**Ans.** 
When operating on two tensors, PyTorch compares their shapes elementwise. It starts with the trailing dimensions and works its way backward, adding 1 when it meets empty dimensions. Two dimensions are compatible when one of the following is true:

They are equal. One of them is 1, in which case that dimension is broadcast to make it the same as the other.
Arrays do not need to have the same number of dimensions. For example, if you have a 256×256×3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with three values. 

Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible:</br>
Image  (3d tensor): 256 x 256 x 3</br>
Scale  (1d tensor):  (1)   (1)  3</br>
Result (3d tensor): 256 x 256 x 3</br>

However, a 2D tensor of size 256×256 isn't compatible with our image:</br>
Image  (3d tensor): 256 x 256 x   3</br>
Scale  (2d tensor):  (1)  256 x 256</br>
Error</br>

In our earlier examples we had with a 3×3 matrix and a vector of size 3, broadcasting was done on the rows:</br>
Matrix (2d tensor):   3 x 3</br>
Vector (1d tensor): (1)   3</br>
Result (2d tensor):   3 x 3</br>

As an exercise, try to determine what dimensions to add (and where) when you need to normalize a batch of images of size 64 x 3 x 256 x 256 with vectors of three elements (one for the mean and one for the standard deviation).

Another useful way of simplifying tensor manipulations is the use of Einstein summations convention.


#### Q15. What is expand_as? Show an example of how it can be used to match the results of broadcasting.

**Ans.** 
Here the elements of c are expanded to make three rows that match, making the operation possible. Again, PyTorch doesn't actually create three copies of c in memory. This is done by the expand_as method behind the scenes:</br>
`c.expand_as(m)
tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])`
        
If we look at the corresponding tensor, we can ask for its storage property (which shows the actual contents of the memory used for the tensor) to check there is no useless data stored:</br>
`t = c.expand_as(m)
t.storage()
 10.0
 20.0
 30.0
[torch.FloatStorage of size 3]`

Even though the tensor officially has nine elements, only three scalars are stored in memory. This is possible thanks to the clever trick of giving that dimension a stride of 0 (which means that when PyTorch looks for the next row by adding the stride, it doesn't move):</br>

`t.stride(), t.shape
((0, 1), torch.Size([3, 3]))`
