# Programming_Assignment_08

#### 1. Write a Python Program to Add Two Matrices?

In [1]:
mat1 = [[8,12,0],[3,2,1],[5,8,2]]
mat2 =[[4,5,6],[7,8,9],[9,8,7]]
res = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(mat1)):
    for j in range(len(mat1[i])):
        res[i][j] = mat1[i][j] + mat2[i][j]
print(res)

[[12, 17, 6], [10, 10, 10], [14, 16, 9]]


#### 2. Write a Python Program to Multiply Two Matrices?

In [2]:
mat1 = [[8,12,0],[3,2,1],[5,8,2]]
mat2 =[[4,5,6],[7,8,9],[9,8,7]]
res = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(mat1)):
    for j in range(len(mat2[0])):
        for k in range(len(mat2)):
            res[i][j] += mat1[i][k] * mat2[k][j]
print(res)

[[116, 136, 156], [35, 39, 43], [94, 105, 116]]


In [3]:
import numpy as np

mat1 = [[8,12,0],[3,2,1],[5,8,2]]
mat2 =[[4,5,6],[7,8,9],[9,8,7]]
np.dot(mat1,mat2)

array([[116, 136, 156],
       [ 35,  39,  43],
       [ 94, 105, 116]])

#### 3. Write a Python Program to Transpose a Matrix?

In [4]:
mat=[[5,4,5],[6,8,9]]
res=[[0,0],[0,0],[0,0]]

for i in range(len(mat)):
    for j in range(len(mat[0])):
        res[j][i] = mat[i][j]
print(res)

[[5, 6], [4, 8], [5, 9]]


In [5]:
import numpy as np

mat=np.array([[5,4,5],[6,8,9]])
print(mat.T)

[[5 6]
 [4 8]
 [5 9]]


In [6]:
import numpy as np

def tpMat(mat):
    tp=np.array(mat)
    print(tp.T)

tpMat([[5, 6], [4, 8], [5, 9]])
tpMat([[1,0,1], [0,1,0], [0,1,0]])

[[5 4 5]
 [6 8 9]]
[[1 0 0]
 [0 1 1]
 [1 0 0]]


#### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
def ascSort(words):
    li = list(words.split(" "))
    li.sort()
    return " ".join(li)

ascSort("zebra cat hog bat cow owl")

'bat cat cow hog owl zebra'

#### 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
words = input()
punct="""!()-[]{};:'"\,<>./?@#$%^&*_~]"""
for i in words:
    if i in punct:
        words = words.replace(i,"")
print(words)


Hello! How are you?
Hello How are you
